<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Experiments with more than one IV | Tools for Working with Data</title>
  <meta name="description" content="This GitBook describes tools students can use to work with data." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Experiments with more than one IV | Tools for Working with Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This GitBook describes tools students can use to work with data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Experiments with more than one IV | Tools for Working with Data" />
  
  <meta name="twitter:description" content="This GitBook describes tools students can use to work with data." />
  

<meta name="author" content="Nicole Sorhagen, Ph.D." />


<meta name="date" content="2020-08-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple-experiments.html"/>
<link rel="next" href="final-words.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Tools for Analyzing data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About this book</a></li>
<li class="chapter" data-level="2" data-path="set-up-project-on-rstudio-cloud.html"><a href="set-up-project-on-rstudio-cloud.html"><i class="fa fa-check"></i><b>2</b> Set up project on Rstudio Cloud</a></li>
<li class="chapter" data-level="3" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>3</b> Introduction</a><ul>
<li class="chapter" data-level="3.1" data-path="introduction.html"><a href="introduction.html#layout-of-rstudio-cloud"><i class="fa fa-check"></i><b>3.1</b> Layout of Rstudio cloud</a><ul>
<li class="chapter" data-level="3.1.1" data-path="introduction.html"><a href="introduction.html#console"><i class="fa fa-check"></i><b>3.1.1</b> Console</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction.html"><a href="introduction.html#script"><i class="fa fa-check"></i><b>3.1.2</b> Script</a></li>
<li class="chapter" data-level="3.1.3" data-path="introduction.html"><a href="introduction.html#environment-and-history"><i class="fa fa-check"></i><b>3.1.3</b> Environment and history</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction.html"><a href="introduction.html#importing-data-into-rstudio-cloud"><i class="fa fa-check"></i><b>3.2</b> Importing data into Rstudio cloud</a><ul>
<li class="chapter" data-level="3.2.1" data-path="introduction.html"><a href="introduction.html#upload-the-data-into-rstudio-cloud"><i class="fa fa-check"></i><b>3.2.1</b> Upload the data into Rstudio Cloud</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction.html"><a href="introduction.html#import-data"><i class="fa fa-check"></i><b>3.2.2</b> Import data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>4</b> Packages</a><ul>
<li class="chapter" data-level="4.1" data-path="packages.html"><a href="packages.html#installing-packages"><i class="fa fa-check"></i><b>4.1</b> Installing packages</a><ul>
<li class="chapter" data-level="4.1.1" data-path="packages.html"><a href="packages.html#installing-packages-using-point-and-click-gui"><i class="fa fa-check"></i><b>4.1.1</b> Installing packages using point and click (GUI)</a></li>
<li class="chapter" data-level="4.1.2" data-path="packages.html"><a href="packages.html#installing-packages-using-code"><i class="fa fa-check"></i><b>4.1.2</b> Installing packages using code</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="packages.html"><a href="packages.html#loading-packages"><i class="fa fa-check"></i><b>4.2</b> Loading Packages</a></li>
<li class="chapter" data-level="4.3" data-path="packages.html"><a href="packages.html#misc"><i class="fa fa-check"></i><b>4.3</b> Misc</a><ul>
<li class="chapter" data-level="4.3.1" data-path="packages.html"><a href="packages.html#restarting-r"><i class="fa fa-check"></i><b>4.3.1</b> Restarting R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="picturing-data.html"><a href="picturing-data.html"><i class="fa fa-check"></i><b>5</b> Picturing Data</a><ul>
<li class="chapter" data-level="5.1" data-path="picturing-data.html"><a href="picturing-data.html#histograms"><i class="fa fa-check"></i><b>5.1</b> Histograms</a><ul>
<li class="chapter" data-level="5.1.1" data-path="picturing-data.html"><a href="picturing-data.html#histograms-with-base-r"><i class="fa fa-check"></i><b>5.1.1</b> Histograms with base R</a></li>
<li class="chapter" data-level="5.1.2" data-path="picturing-data.html"><a href="picturing-data.html#histograms-with-tidyverse"><i class="fa fa-check"></i><b>5.1.2</b> Histograms with tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="picturing-data.html"><a href="picturing-data.html#scatterplots"><i class="fa fa-check"></i><b>5.2</b> Scatterplots</a><ul>
<li class="chapter" data-level="5.2.1" data-path="picturing-data.html"><a href="picturing-data.html#two-continuous-variables"><i class="fa fa-check"></i><b>5.2.1</b> Two continuous variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="picturing-data.html"><a href="picturing-data.html#one-continuous-and-one-categorical-variable"><i class="fa fa-check"></i><b>5.2.2</b> One continuous and one categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="picturing-data.html"><a href="picturing-data.html#additional-resources"><i class="fa fa-check"></i><b>5.3</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>6</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-using-tidyverse-and-psych-packages."><i class="fa fa-check"></i><b>6.1</b> Descriptive statistics using Tidyverse and Psych packages.</a></li>
<li class="chapter" data-level="6.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-using-base-r"><i class="fa fa-check"></i><b>6.2</b> Descriptive statistics using base R</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="measurement.html"><a href="measurement.html"><i class="fa fa-check"></i><b>7</b> Measurement</a><ul>
<li class="chapter" data-level="7.1" data-path="measurement.html"><a href="measurement.html#a-brief-introduction-to-spreadsheets-and-some-brief-review-of-previous-material"><i class="fa fa-check"></i><b>7.1</b> A brief introduction to spreadsheets (and some brief review of previous material)</a></li>
<li class="chapter" data-level="7.2" data-path="measurement.html"><a href="measurement.html#reliability"><i class="fa fa-check"></i><b>7.2</b> Reliability</a><ul>
<li class="chapter" data-level="7.2.1" data-path="measurement.html"><a href="measurement.html#internal-reliability"><i class="fa fa-check"></i><b>7.2.1</b> Internal reliability</a></li>
<li class="chapter" data-level="7.2.2" data-path="measurement.html"><a href="measurement.html#test-retest-reliability"><i class="fa fa-check"></i><b>7.2.2</b> Test-retest reliability</a></li>
<li class="chapter" data-level="7.2.3" data-path="measurement.html"><a href="measurement.html#interrater-reliability"><i class="fa fa-check"></i><b>7.2.3</b> Interrater reliability</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="measurement.html"><a href="measurement.html#validity"><i class="fa fa-check"></i><b>7.3</b> Validity</a><ul>
<li class="chapter" data-level="7.3.1" data-path="measurement.html"><a href="measurement.html#criterion-validity"><i class="fa fa-check"></i><b>7.3.1</b> Criterion validity</a></li>
<li class="chapter" data-level="7.3.2" data-path="measurement.html"><a href="measurement.html#convergent-and-discriminant-validity"><i class="fa fa-check"></i><b>7.3.2</b> Convergent and Discriminant Validity</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="measurement.html"><a href="measurement.html#homework"><i class="fa fa-check"></i><b>7.4</b> Homework</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="basic-data-transformations.html"><a href="basic-data-transformations.html"><i class="fa fa-check"></i><b>8</b> Basic Data Transformations</a></li>
<li class="chapter" data-level="9" data-path="bivariate-correlational-research.html"><a href="bivariate-correlational-research.html"><i class="fa fa-check"></i><b>9</b> Bivariate correlational research</a><ul>
<li class="chapter" data-level="9.1" data-path="bivariate-correlational-research.html"><a href="bivariate-correlational-research.html#association-claim-with-two-quantitative-variables"><i class="fa fa-check"></i><b>9.1</b> Association claim with two quantitative variables</a></li>
<li class="chapter" data-level="9.2" data-path="bivariate-correlational-research.html"><a href="bivariate-correlational-research.html#association-claim-with-one-quantitative-variable-and-one-categorical-variable"><i class="fa fa-check"></i><b>9.2</b> Association claim with one quantitative variable and one categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html"><i class="fa fa-check"></i><b>10</b> Multivariate correlational research</a><ul>
<li class="chapter" data-level="10.1" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#get-to-know-data"><i class="fa fa-check"></i><b>10.1</b> Get to know data</a></li>
<li class="chapter" data-level="10.2" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#multiple-regression"><i class="fa fa-check"></i><b>10.2</b> Multiple regression</a><ul>
<li class="chapter" data-level="10.2.1" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#optional-additional-information"><i class="fa fa-check"></i><b>10.2.1</b> Optional additional information</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#mediation-and-moderation"><i class="fa fa-check"></i><b>10.3</b> Mediation and moderation</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="simple-experiments.html"><a href="simple-experiments.html"><i class="fa fa-check"></i><b>11</b> Simple experiments</a><ul>
<li class="chapter" data-level="11.1" data-path="simple-experiments.html"><a href="simple-experiments.html#two-groups---independent-group-design"><i class="fa fa-check"></i><b>11.1</b> Two groups - Independent group design</a><ul>
<li class="chapter" data-level="11.1.1" data-path="simple-experiments.html"><a href="simple-experiments.html#research-question"><i class="fa fa-check"></i><b>11.1.1</b> Research question</a></li>
<li class="chapter" data-level="11.1.2" data-path="simple-experiments.html"><a href="simple-experiments.html#method"><i class="fa fa-check"></i><b>11.1.2</b> Method</a></li>
<li class="chapter" data-level="11.1.3" data-path="simple-experiments.html"><a href="simple-experiments.html#data-analysis"><i class="fa fa-check"></i><b>11.1.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="simple-experiments.html"><a href="simple-experiments.html#two-groups---dependent-group-design"><i class="fa fa-check"></i><b>11.2</b> Two groups - Dependent group design</a><ul>
<li class="chapter" data-level="11.2.1" data-path="simple-experiments.html"><a href="simple-experiments.html#research-question-1"><i class="fa fa-check"></i><b>11.2.1</b> Research question</a></li>
<li class="chapter" data-level="11.2.2" data-path="simple-experiments.html"><a href="simple-experiments.html#method-1"><i class="fa fa-check"></i><b>11.2.2</b> Method</a></li>
<li class="chapter" data-level="11.2.3" data-path="simple-experiments.html"><a href="simple-experiments.html#data-analysis-1"><i class="fa fa-check"></i><b>11.2.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="simple-experiments.html"><a href="simple-experiments.html#more-than-two-groups---independent-group-design"><i class="fa fa-check"></i><b>11.3</b> More than two groups - Independent group design</a><ul>
<li class="chapter" data-level="11.3.1" data-path="simple-experiments.html"><a href="simple-experiments.html#research-question-2"><i class="fa fa-check"></i><b>11.3.1</b> Research question</a></li>
<li class="chapter" data-level="11.3.2" data-path="simple-experiments.html"><a href="simple-experiments.html#method-2"><i class="fa fa-check"></i><b>11.3.2</b> Method</a></li>
<li class="chapter" data-level="11.3.3" data-path="simple-experiments.html"><a href="simple-experiments.html#data-analysis-2"><i class="fa fa-check"></i><b>11.3.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="simple-experiments.html"><a href="simple-experiments.html#more-than-two-groups---dependent-group-design"><i class="fa fa-check"></i><b>11.4</b> More than two groups - Dependent group design</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html"><i class="fa fa-check"></i><b>12</b> Experiments with more than one IV</a><ul>
<li class="chapter" data-level="12.1" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#research-question-3"><i class="fa fa-check"></i><b>12.1</b> Research question</a></li>
<li class="chapter" data-level="12.2" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#methods"><i class="fa fa-check"></i><b>12.2</b> Methods</a></li>
<li class="chapter" data-level="12.3" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#data-analysis-3"><i class="fa fa-check"></i><b>12.3</b> Data analysis</a><ul>
<li class="chapter" data-level="12.3.1" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#open-data-and-load-the-necessary-packages.-1"><i class="fa fa-check"></i><b>12.3.1</b> Open data and load the necessary packages.</a></li>
<li class="chapter" data-level="12.3.2" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#get-to-know-data-1"><i class="fa fa-check"></i><b>12.3.2</b> Get to know data</a></li>
<li class="chapter" data-level="12.3.3" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#stats-3"><i class="fa fa-check"></i><b>12.3.3</b> Stats</a></li>
<li class="chapter" data-level="12.3.4" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#apa-style-write-up-2"><i class="fa fa-check"></i><b>12.3.4</b> APA-style write up</a></li>
<li class="chapter" data-level="12.3.5" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#bonus-optional-material-apatables"><i class="fa fa-check"></i><b>12.3.5</b> Bonus / optional material: apaTables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>13</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tools for Working with Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="experiments-with-more-than-one-iv" class="section level1">
<h1><span class="header-section-number">Chapter 12</span> Experiments with more than one IV</h1>
<div id="research-question-3" class="section level2">
<h2><span class="header-section-number">12.1</span> Research question</h2>
<p>Previous research suggests that people tend to seek help from a computer program more often when the computer has human-like features. Kim, Zhang, and Park (2018) tested whether this preference for anthropomorphic helpers depends on individual differences in the way that people think about the malleability of intelligence, or their theory of intelligence (TOI). With an entity TOI, intelligence is thought of as fixed and unchangeable. With an incremental TOI, intelligence is thought of a malleable and changeable.</p>
</div>
<div id="methods" class="section level2">
<h2><span class="header-section-number">12.2</span> Methods</h2>
<p>Kim, Zhang, and Park (2018) recruited 171 undergraduate students. All of the participants were asked to complete an intelligence test and were told they could ask the computer for help on the questions if needed.</p>
<p>They experimentally manipulated TOI by having participants randomly assigned to the entity condition -which consisted of participants reading an article that supports entity theory (e.g., “neither environmental factors nor intense willpower appear to change this basic stability of intelligence”). Those assigned to the incremental condition read an article supporting an incremental theory (e.g., “intelligence seems to be rather malleable and to develop significantly over time”). A manipulation check found that participants in the entity theory condition expressed a stronger belief in fixed intelligence (M = 4.59, SD = 1.54, 95% CI = [4.25, 4.93]) than did those in the incremental-theory condition (M = 2.67, SD = 1.37, 95% CI = [2.38, 2.96]), t(169) = 8.63, p &lt; .001, d = 1.32, 95% CI for d = [0.99, 1.65]. (<strong>Note that the statistics and research methods terms (like manipulation check) in this last sentence should make sense to you now.</strong>)</p>
<p>Kim, Zhang, and Park (2018) also randomly assigned their participants to an anthropomorphism condition, where participants received help from a computer-shaped icon with a humanlike face and with the hint placed inside a speech bubble, or to a nonanthropomorphism condition, where participants received help from a computer-shaped icon without a humanlike face, and the hint text did not appear in a speech bubble.</p>
<p><img src="img/anthropomor.png" /></p>
<p>Kim, Zhang, and Park (2018) made their data publicly available. Let’s reproduce their analysis testing for difference in the number of times the participants asked for help from the computer program by the two independent variables (TOI and anthropomorphism).</p>
</div>
<div id="data-analysis-3" class="section level2">
<h2><span class="header-section-number">12.3</span> Data analysis</h2>
<p>Psychologists use a factorial ANOVAs to test for differences between groups in experiments with more than one IV.</p>
<div id="open-data-and-load-the-necessary-packages.-1" class="section level3">
<h3><span class="header-section-number">12.3.1</span> Open data and load the necessary packages.</h3>
<p>Load the data onto your RStudio Cloud project which is in the Study2_Final.csv file on D2L.</p>
<p>Here is the <a href="https://osf.io/ys9a5/">codebook</a></p>
<p>After you load it into your RStudio cloud project, open the data with the IMPORT DATASET point and click method, or with this code:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="experiments-with-more-than-one-iv.html#cb130-1"></a><span class="kw">library</span>(readr)</span>
<span id="cb130-2"><a href="experiments-with-more-than-one-iv.html#cb130-2"></a></span>
<span id="cb130-3"><a href="experiments-with-more-than-one-iv.html#cb130-3"></a>park &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;Study2_Final.csv&quot;</span>)</span></code></pre></div>
<p>Then load the tidyverse and psych packages with this code:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="experiments-with-more-than-one-iv.html#cb131-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb131-2"><a href="experiments-with-more-than-one-iv.html#cb131-2"></a><span class="kw">library</span>(psych)</span></code></pre></div>
</div>
<div id="get-to-know-data-1" class="section level3">
<h3><span class="header-section-number">12.3.2</span> Get to know data</h3>
<p>Let’s first create new categorical text-based variables from the numeric IV variables in the data (Anthropomorphism and TheoryofIntelligence). This is needed to run the factorial ANOVA below. Let’s just do it now because the text also makes the output easier to read compared to remembering what 0 and 1 represent, especially with more than one IV.</p>
<p>We will use the <code>mutate()</code> function of tidyverse to do this. Remember that the old variable should be on the left and it must be in back ticks when it is a number. String (AKA text) variables should be in quotes instead of back ticks.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="experiments-with-more-than-one-iv.html#cb132-1"></a> park &lt;-<span class="st"> </span>park <span class="op">%&gt;%</span></span>
<span id="cb132-2"><a href="experiments-with-more-than-one-iv.html#cb132-2"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">Anthropomorphismf =</span><span class="kw">recode</span>(Anthropomorphism, <span class="st">`</span><span class="dt">0</span><span class="st">`</span> =<span class="st"> &quot;Nonanthropomorphic&quot;</span>, <span class="st">`</span><span class="dt">1</span><span class="st">`</span> =<span class="st"> &quot;Anthropomorphism&quot;</span>))</span>
<span id="cb132-3"><a href="experiments-with-more-than-one-iv.html#cb132-3"></a> </span>
<span id="cb132-4"><a href="experiments-with-more-than-one-iv.html#cb132-4"></a>park &lt;-<span class="st"> </span>park <span class="op">%&gt;%</span></span>
<span id="cb132-5"><a href="experiments-with-more-than-one-iv.html#cb132-5"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">TheoryofIntelligencef =</span><span class="kw">recode</span>(TheoryofIntelligence, <span class="st">`</span><span class="dt">0</span><span class="st">`</span> =<span class="st"> &quot;Incremental&quot;</span>, <span class="st">`</span><span class="dt">1</span><span class="st">`</span> =<span class="st"> &quot;Entity&quot;</span>))</span></code></pre></div>
<p>Then compute measures of central tendency and variability by groups with the <code>describeBy()</code> function of the psych package. With two grouping variables, after the DV add <code>list()</code> and include both IVs in the parenthesis.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="experiments-with-more-than-one-iv.html#cb133-1"></a><span class="kw">describeBy</span>(park<span class="op">$</span>Total_NumberofHelp,<span class="kw">list</span>(park<span class="op">$</span>Anthropomorphismf,park<span class="op">$</span>TheoryofIntelligencef))</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## : Anthropomorphism
## : Entity
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 40  8.7 5.11    9.5    8.94 5.93   0  16    16 -0.34    -1.23 0.81
## ------------------------------------------------------------ 
## : Nonanthropomorphic
## : Entity
##    vars  n  mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 43 11.09 3.83     11   11.49 4.45   0  16    16 -0.91     0.51 0.58
## ------------------------------------------------------------ 
## : Anthropomorphism
## : Incremental
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 49 9.53 3.37     10    9.61 2.97   1  16    15 -0.35    -0.01 0.48
## ------------------------------------------------------------ 
## : Nonanthropomorphic
## : Incremental
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 39 8.74 4.19      8    8.82 4.45   0  16    16 -0.09    -0.96 0.67</code></pre>
<p>Finally, let’s create of plot of the mean number of times the participants sought help by the two IVs. To this add <code>group = TheoryofIntelligence, color = TheoryofIntelligence</code> to the <code>aes()</code> function within the ggplot function.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="experiments-with-more-than-one-iv.html#cb135-1"></a><span class="kw">ggplot</span>(park, <span class="kw">aes</span>(<span class="dt">x =</span> Anthropomorphismf, <span class="dt">y =</span> Total_NumberofHelp, <span class="dt">group =</span> TheoryofIntelligencef, <span class="dt">color =</span> TheoryofIntelligencef)) <span class="op">+</span></span>
<span id="cb135-2"><a href="experiments-with-more-than-one-iv.html#cb135-2"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_cl_normal) </span></code></pre></div>
<p><img src="Tools-for-Working-with-Data_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>You could also add a line in order to easily see the interaction by adding <code>stat_summary(fun = mean, geom = "line")</code> to the command.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="experiments-with-more-than-one-iv.html#cb136-1"></a><span class="kw">ggplot</span>(park, <span class="kw">aes</span>(<span class="dt">x =</span> Anthropomorphismf, <span class="dt">y =</span> Total_NumberofHelp, <span class="dt">group =</span> TheoryofIntelligencef, <span class="dt">color =</span> TheoryofIntelligencef)) <span class="op">+</span></span>
<span id="cb136-2"><a href="experiments-with-more-than-one-iv.html#cb136-2"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_cl_normal) <span class="op">+</span></span>
<span id="cb136-3"><a href="experiments-with-more-than-one-iv.html#cb136-3"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun =</span> mean, <span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>)</span></code></pre></div>
<p><img src="Tools-for-Working-with-Data_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p><strong>Interpretation</strong></p>
<p>There is a clear interaction between the Anthropomorphism condition and the TOI condition. Participants in the entity condition sought more help in the non-anthropomorphic condition compared to the anthropomorphic condition. The participants in the incremental condition, on the other hand, sought more help in the anthropomorphic condition compared to the non-anthropomorphic condition.</p>
</div>
<div id="stats-3" class="section level3">
<h3><span class="header-section-number">12.3.3</span> Stats</h3>
<p>We will analyze the data with a 2(anthropomorphism:yes v no) X 2 (TOI: entity v incremental) factorial ANOVA.</p>
<p>Let’s start by creating the model using the <code>aov()</code> function. Remember that this function takes the form of <code>DV ~ IV</code>. With multiple IVs it takes the form of <code>DV ~ IV1 + IV2</code>. Add <code>IV1:IV2</code> to test the interaction (i.e. <code>DV ~ IV1 + IV2 + IV1:IV2</code>).</p>
<p>I called the object parkfano for park factorial ANOVA.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="experiments-with-more-than-one-iv.html#cb137-1"></a>parkfano &lt;-<span class="st"> </span><span class="kw">aov</span>(Total_NumberofHelp <span class="op">~</span><span class="st"> </span>Anthropomorphismf <span class="op">+</span><span class="st"> </span>TheoryofIntelligencef <span class="op">+</span><span class="st"> </span>Anthropomorphismf<span class="op">:</span>TheoryofIntelligencef, <span class="dt">data =</span> park)</span></code></pre></div>
<p>Then call the model with the <code>summary()</code> function to view the results.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="experiments-with-more-than-one-iv.html#cb138-1"></a><span class="kw">summary</span>(parkfano)</span></code></pre></div>
<pre><code>##                                          Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Anthropomorphismf                         1   28.6   28.58   1.678  0.197  
## TheoryofIntelligencef                     1   20.8   20.85   1.224  0.270  
## Anthropomorphismf:TheoryofIntelligencef   1  107.2  107.23   6.298  0.013 *
## Residuals                               167 2843.7   17.03                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Interpretation</strong></p>
<p>The first line shows the statistics related to the main effect of Anthropomorphism. The p-value (0.197) associated with the f-value (1.678) is greater than .05, and therefore is not statistically significant.</p>
<p>The second line shows the statistics for the main effect of TOI. The p-value (0.270) associated with the f-value (1.224) is greater than .05, so this is also not statistically significant.</p>
<p>The third line shows the statistics for the interaction between Anthropomorphism and TOI. The interaction was statistically significant, as the p-value (0.013) associated with the f-value (6.298) is less than .05.</p>
<p>Eta-squared is a common measure of effect size for an ANOVA. It can be interpreted in the same way as R-squared in regression (the proportion of the DV that is accounted for by an IV).</p>
<p>Eta-squared is very easy to calculate. It is the sum of squares for an effect divided by the total sum of squares. So you could pretty quickly do this by hand. For example the eta-squared for the interaction is <code>107.2/3000.3</code> is 0.0357298 (note that SS total = <code>28.6+20.8+107.2+2843.7</code>). This tell us that the interaction accounts for 0.0357298 of the variance in the help seeking variable, which is rather small.</p>
<p>Of course you could also have R do these calculations for you. There are a few packages that commute effect sizes for ANOVA. I like the lsr package, which is maintained by Danielle Navarra.</p>
<p>First install it:<br />
<code>install.packages("lsr")</code></p>
<p>Then load it:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="experiments-with-more-than-one-iv.html#cb140-1"></a><span class="kw">library</span>(lsr)</span></code></pre></div>
<p>This package has a <code>etaSquared()</code> function. Put the name of the object containing the factorial ANOVA in the parenthesis.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="experiments-with-more-than-one-iv.html#cb141-1"></a><span class="kw">etaSquared</span>(parkfano)</span></code></pre></div>
<pre><code>##                                              eta.sq eta.sq.part
## Anthropomorphismf                       0.008295075 0.008676123
## TheoryofIntelligencef                   0.006948311 0.007277745
## Anthropomorphismf:TheoryofIntelligencef 0.035740724 0.036339358</code></pre>
<p>The numbers below the et.sq are the eta-squares for each main effect and the interaction. The next column is the partial eta-squares, which is the ratio of variance associated with an effect ignoring the other effects in the factorial ANOVA.</p>
<p><strong>Interpretation</strong></p>
<p>The eta-squared (0.035740724) and the partial eta-squared (0.036339358) tells us that the interaction between Anthropomorphism and TOI accounts for about 3.5% of the total variance in help seeking behaviors.</p>
<p>Next we need to run post-hoc analysis to determine which groups involved in the interaction are different from each other. Let’s first look at the group means. You could scroll up to the descriptives we ran above.</p>
<p>Or you could use the <code>model.tables()</code> function, which is part of base R. Put the model name in the parenthesis followed by <code>type="means"</code>. <code>model.tables()</code> is nice to use because it includes the DV’s grand mean, the main effect means, and the interaction means.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="experiments-with-more-than-one-iv.html#cb143-1"></a><span class="kw">model.tables</span>(parkfano, <span class="dt">type=</span><span class="st">&quot;means&quot;</span>)</span></code></pre></div>
<pre><code>## Tables of means
## Grand mean
##          
## 9.549708 
## 
##  Anthropomorphismf 
##     Anthropomorphism Nonanthropomorphic
##                9.157              9.976
## rep           89.000             82.000
## 
##  TheoryofIntelligencef 
##     Entity Incremental
##      9.908       9.212
## rep 83.000      88.000
## 
##  Anthropomorphismf:TheoryofIntelligencef 
##                     TheoryofIntelligencef
## Anthropomorphismf    Entity Incremental
##   Anthropomorphism    8.70   9.53      
##   rep                40.00  49.00      
##   Nonanthropomorphic 11.09   8.74      
##   rep                43.00  39.00</code></pre>
<p>So the grand mean (9.549708) is the mean number of times of all of the participants in the study sought help from the computer.</p>
<p>Next are the means for the number of help seeking for the Anthropomorphism main effect. The mean of the anthropomorphism group (9.157) is not different from the nonanthropomorphism (9.976). Rep mean number of participants. 89 participants were in the anthropomorphism condition and 82 were in the nonanthropomorphic condition.</p>
<p>Next are the means for the TOI main effect. The mean of the Entity group (9.908) is not different from the Incremental group (9.212).</p>
<p>The last table is the cell means for the interaction. These are the means we need to test to see where the difference between groups are.</p>
<p>One way to probe the interaction is to use the Tukey HSD host-hoc test function - as we did with the one-way ANOVA. Put the object with the ANOVA results in the parenthesis of the <code>TukeyHSD()</code>function.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="experiments-with-more-than-one-iv.html#cb145-1"></a><span class="kw">TukeyHSD</span>(parkfano)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Total_NumberofHelp ~ Anthropomorphismf + TheoryofIntelligencef + Anthropomorphismf:TheoryofIntelligencef, data = park)
## 
## $Anthropomorphismf
##                                          diff        lwr      upr     p adj
## Nonanthropomorphic-Anthropomorphism 0.8183064 -0.4287442 2.065357 0.1969344
## 
## $TheoryofIntelligencef
##                          diff       lwr       upr     p adj
## Incremental-Entity -0.6966575 -1.943196 0.5498808 0.2714547
## 
## $`Anthropomorphismf:TheoryofIntelligencef`
##                                                                    diff
## Nonanthropomorphic:Entity-Anthropomorphism:Entity            2.39302326
## Anthropomorphism:Incremental-Anthropomorphism:Entity         0.83061224
## Nonanthropomorphic:Incremental-Anthropomorphism:Entity       0.04358974
## Anthropomorphism:Incremental-Nonanthropomorphic:Entity      -1.56241101
## Nonanthropomorphic:Incremental-Nonanthropomorphic:Entity    -2.34943351
## Nonanthropomorphic:Incremental-Anthropomorphism:Incremental -0.78702250
##                                                                     lwr
## Nonanthropomorphic:Entity-Anthropomorphism:Entity            0.04064076
## Anthropomorphism:Incremental-Anthropomorphism:Entity        -1.45130601
## Nonanthropomorphic:Incremental-Anthropomorphism:Entity      -2.36622891
## Anthropomorphism:Incremental-Nonanthropomorphic:Entity      -3.80007443
## Nonanthropomorphic:Incremental-Nonanthropomorphic:Entity    -4.71738887
## Nonanthropomorphic:Incremental-Anthropomorphism:Incremental -3.08499120
##                                                                    upr
## Nonanthropomorphic:Entity-Anthropomorphism:Entity           4.74540575
## Anthropomorphism:Incremental-Anthropomorphism:Entity        3.11253050
## Nonanthropomorphic:Incremental-Anthropomorphism:Entity      2.45340840
## Anthropomorphism:Incremental-Nonanthropomorphic:Entity      0.67525240
## Nonanthropomorphic:Incremental-Nonanthropomorphic:Entity    0.01852185
## Nonanthropomorphic:Incremental-Anthropomorphism:Incremental 1.51094619
##                                                                 p adj
## Nonanthropomorphic:Entity-Anthropomorphism:Entity           0.0445113
## Anthropomorphism:Incremental-Anthropomorphism:Entity        0.7808214
## Nonanthropomorphic:Incremental-Anthropomorphism:Entity      0.9999627
## Anthropomorphism:Incremental-Nonanthropomorphic:Entity      0.2713317
## Nonanthropomorphic:Incremental-Nonanthropomorphic:Entity    0.0526680
## Nonanthropomorphic:Incremental-Anthropomorphism:Incremental 0.8106932</code></pre>
<p>The results start with testing the main effects (we no there will be no difference because the main effects in the factorial ANOVA were not statistically significant).</p>
<p>Then are the cell mean comparisons (below <code>$</code>Anthropomorphismf:TheoryofIntelligencef``).</p>
<p>The only statistically significant difference is between the mean of the Nonanthropomorphic and Entity and the Anthropomorphism and Entity cells (the first comparison). The point estimate of this difference is 2.39302326. An interval estimate is 0.04064076 to 4.74540575 - showing a fair amount of uncertainty.</p>
<p>Another option to probe the interaction is is to run a t-test separately for each level of one of the IVs. We will use the <code>filter()</code> function to select the levels. This function allows you to pick observations or rows by their values. The operations you can use to select a subset of values are: &gt;, &gt;=, &lt;, &lt;=, != (not equal), and == (equal). In this example let’s first select the participants that were in the entity condition first. To do this we should put <code>TheoryofIntelligence == 1</code> in the parenthesis. Let’s also save this as a new object called <code>parkent</code> for park-entity.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="experiments-with-more-than-one-iv.html#cb147-1"></a>parkent &lt;-<span class="st"> </span>park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb147-2"><a href="experiments-with-more-than-one-iv.html#cb147-2"></a><span class="st">  </span><span class="kw">filter</span>(TheoryofIntelligence <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</span></code></pre></div>
<p>Then using this new dataset, use a independent sample t-test and cohen’s d to test for differences in help seeking by Anthropomorphism condition.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="experiments-with-more-than-one-iv.html#cb148-1"></a><span class="kw">t.test</span>(Total_NumberofHelp <span class="op">~</span><span class="st"> </span>Anthropomorphismf, <span class="dt">data =</span> parkent, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Total_NumberofHelp by Anthropomorphismf
## t = -2.4269, df = 81, p-value = 0.01745
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.3549407 -0.4311059
## sample estimates:
##   mean in group Anthropomorphism mean in group Nonanthropomorphic 
##                          8.70000                         11.09302</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="experiments-with-more-than-one-iv.html#cb150-1"></a><span class="kw">library</span>(effsize)</span>
<span id="cb150-2"><a href="experiments-with-more-than-one-iv.html#cb150-2"></a><span class="kw">cohen.d</span>(Total_NumberofHelp <span class="op">~</span><span class="st"> </span>Anthropomorphismf, <span class="dt">data =</span> parkent)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: -0.5331208 (medium)
## 95 percent confidence interval:
##       lower       upper 
## -0.97788567 -0.08835596</code></pre>
<p>The results show that the 95% CI is -4.3549407 to -0.4311059, which means that the true difference in the number of times participants sought help based on Anthropomorphism condition use is likely to be between about a half to about four times.</p>
<p>The results also report that t = -2.4269, df = 81, p-value = 0.01745 - so the difference is statistically significant.</p>
<p>The Cohen’s d is -0.5331208, which is a medium effect. The 95% CI is -0.08835596 to -0.97788567 - indicating that the true size of the effect is close to zero to around 1.</p>
<p>Next do the same for the participants in the incremental condition. First create an object with just the incremental participants.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="experiments-with-more-than-one-iv.html#cb152-1"></a>parkinc &lt;-<span class="st"> </span>park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb152-2"><a href="experiments-with-more-than-one-iv.html#cb152-2"></a><span class="st">  </span><span class="kw">filter</span>(TheoryofIntelligence <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</span></code></pre></div>
<p>Then using this new dataset, use a independent sample t-test and cohen’s d to test for differences in help seeking by Anthropomorphism condition.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="experiments-with-more-than-one-iv.html#cb153-1"></a><span class="kw">t.test</span>(Total_NumberofHelp <span class="op">~</span><span class="st"> </span>Anthropomorphismf, <span class="dt">data =</span> parkinc, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Total_NumberofHelp by Anthropomorphismf
## t = 0.9771, df = 86, p-value = 0.3313
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.8141959  2.3882409
## sample estimates:
##   mean in group Anthropomorphism mean in group Nonanthropomorphic 
##                         9.530612                         8.743590</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="experiments-with-more-than-one-iv.html#cb155-1"></a><span class="kw">cohen.d</span>(Total_NumberofHelp <span class="op">~</span><span class="st"> </span>Anthropomorphismf, <span class="dt">data =</span> parkinc)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 0.2096764 (small)
## 95 percent confidence interval:
##      lower      upper 
## -0.2180713  0.6374242</code></pre>
<p>The results show that the 95% CI is -0.8141959 to 2.3882409, which means that zero is a potential true difference in the number of times participants sought help based on Anthropomorphism condition.</p>
<p>The results also report that t = 0.9771, df = 86, p-value = 0.3313 - so the difference is not statistically significant.</p>
<p>The Cohen’s d is 0.2096764, which is a small effect. The 95% CI is -0.2180713 to 0.6374242 - again indicating that the true size of the effect is potentially zero.</p>
</div>
<div id="apa-style-write-up-2" class="section level3">
<h3><span class="header-section-number">12.3.4</span> APA-style write up</h3>
<p>A 2 (TOI: entity vs. incremental) × 2 (anthropomorphism:yes vs. no) factorial analysis of variance (ANOVA) revealed nonsignificant main effects, ps &gt;.20, but a significant interaction, F(1, 167) = 6.30, p = .013, Partial eta-squared = .04. Tukey HSD post-hoc analysis revealed that the participants in the entity conditions asked for help more often in the nonanthropomorphic condition (M = 11.09, SD = 3.83) than the anthropomorphic condition (M = 8.7, SD = 5.1), 95% CI of difference = 0.04 to 4.75.</p>
</div>
<div id="bonus-optional-material-apatables" class="section level3">
<h3><span class="header-section-number">12.3.5</span> Bonus / optional material: apaTables</h3>
<p>The apaTables package will create an APA style ANOVA table. Like with the multiple regression table, you will need to first rerun the Factorial ANOVA with the <code>lm()</code> function.</p>
<p>Then use the <code>apa.aov.table()</code> function. Put the name of the lm model in the parenthesis, followed by <code>filename = "parkfactANOVA.doc"</code>, and then <code>table.number = 7</code>. Note that you can change the file name to whatever you want - just include the .doc.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="experiments-with-more-than-one-iv.html#cb157-1"></a><span class="kw">library</span>(apaTables)</span>
<span id="cb157-2"><a href="experiments-with-more-than-one-iv.html#cb157-2"></a></span>
<span id="cb157-3"><a href="experiments-with-more-than-one-iv.html#cb157-3"></a>parkfanoAPA &lt;-<span class="st"> </span><span class="kw">lm</span>(Total_NumberofHelp <span class="op">~</span><span class="st"> </span>Anthropomorphismf <span class="op">+</span><span class="st"> </span>TheoryofIntelligencef <span class="op">+</span><span class="st"> </span>Anthropomorphismf<span class="op">:</span>TheoryofIntelligencef, <span class="dt">data =</span> park)</span>
<span id="cb157-4"><a href="experiments-with-more-than-one-iv.html#cb157-4"></a></span>
<span id="cb157-5"><a href="experiments-with-more-than-one-iv.html#cb157-5"></a><span class="kw">apa.aov.table</span>(parkfanoAPA, <span class="dt">filename =</span> <span class="st">&quot;parkfactANOVA.doc&quot;</span>, <span class="dt">table.number =</span> <span class="dv">7</span>)</span></code></pre></div>
<pre><code>## 
## 
## Table 7 
## 
## ANOVA results using Total_NumberofHelp as the dependent variable
##  
## 
##                                  Predictor      SS  df      MS      F    p
##                                (Intercept) 3027.60   1 3027.60 177.80 .000
##                          Anthropomorphismf  118.67   1  118.67   6.97 .009
##                      TheoryofIntelligencef   15.19   1   15.19   0.89 .346
##  Anthropomorphismf x TheoryofIntelligencef  107.23   1  107.23   6.30 .013
##                                      Error 2843.67 167   17.03            
##  partial_eta2 CI_90_partial_eta2
##                                 
##           .04         [.01, .10]
##           .01         [.00, .04]
##           .04         [.00, .09]
##                                 
## 
## Note: Values in square brackets indicate the bounds of the 90% confidence interval for partial eta-squared</code></pre>
<p>Use the table that is saved in the parkfactANOVA.doc file for presentation purposes, as it has all aspects of APA-styled formatting. Also, note that the ANOVA tables include the eta-squared and partial eta-squared (!).</p>
<p>This package will also create a table of means and standard deviations. To do this use the <code>apa.2way.table()</code> function. In the parenthesis list the names of the IVs after <code>IV1 =</code> and <code>IV 2 =</code>. Then list the name of the DV variable after <code>DV =</code>. This is followed by the data object after <code>data =</code>. Then include: <code>filename = "parkmeans.doc", show.marginal.means = TRUE, table.number = 8)</code>. Again - you can change the file name to whatever you want (but don’t forget the .doc).</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="experiments-with-more-than-one-iv.html#cb159-1"></a><span class="kw">apa.2way.table</span>(<span class="dt">iv1 =</span> Anthropomorphismf,<span class="dt">iv2 =</span> TheoryofIntelligencef, <span class="dt">dv =</span> Total_NumberofHelp, </span>
<span id="cb159-2"><a href="experiments-with-more-than-one-iv.html#cb159-2"></a>               <span class="dt">data =</span> park, </span>
<span id="cb159-3"><a href="experiments-with-more-than-one-iv.html#cb159-3"></a>               <span class="dt">filename =</span> <span class="st">&quot;parkmeans.doc&quot;</span>, </span>
<span id="cb159-4"><a href="experiments-with-more-than-one-iv.html#cb159-4"></a>               <span class="dt">show.marginal.means =</span> <span class="ot">TRUE</span>,</span>
<span id="cb159-5"><a href="experiments-with-more-than-one-iv.html#cb159-5"></a>               <span class="dt">table.number =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## 
## 
## Table 8 
## 
## Means and standard deviations for Total_NumberofHelp as a function of a 2(Anthropomorphismf) X 2(TheoryofIntelligencef) design 
## 
##                     TheoryofIntelligencef                                    
##                                    Entity      Incremental      Marginal     
##   Anthropomorphismf                     M   SD           M   SD        M   SD
##    Anthropomorphism                  8.70 5.11        9.53 3.37     9.16 4.23
##  Nonanthropomorphic                 11.09 3.83        8.74 4.19     9.98 4.15
##            Marginal                  9.94 4.62        9.18 3.75              
## 
## Note. M and SD represent mean and standard deviation, respectively. 
## Marginal indicates the means and standard deviations pertaining to main effects.</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-experiments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="final-words.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/nsorha/potential-barnacle/edit/master/moreexper.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Tools for Working with Data.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
