<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Simple experiment | Tools for Working with Data</title>
  <meta name="description" content="This GitBook describes tools students can use to work with data." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Simple experiment | Tools for Working with Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This GitBook describes tools students can use to work with data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Simple experiment | Tools for Working with Data" />
  
  <meta name="twitter:description" content="This GitBook describes tools students can use to work with data." />
  

<meta name="author" content="Nicole Sorhagen, Ph.D." />


<meta name="date" content="2020-07-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multivariate-correlational-research.html"/>
<link rel="next" href="experiments-with-more-than-one-iv.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Tools for Analyzing data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About this book</a></li>
<li class="chapter" data-level="2" data-path="set-up-project-on-rstudio-cloud.html"><a href="set-up-project-on-rstudio-cloud.html"><i class="fa fa-check"></i><b>2</b> Set up project on Rstudio Cloud</a></li>
<li class="chapter" data-level="3" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>3</b> Introduction</a><ul>
<li class="chapter" data-level="3.1" data-path="introduction.html"><a href="introduction.html#layout-of-rstudio-cloud"><i class="fa fa-check"></i><b>3.1</b> Layout of Rstudio cloud</a><ul>
<li class="chapter" data-level="3.1.1" data-path="introduction.html"><a href="introduction.html#console"><i class="fa fa-check"></i><b>3.1.1</b> Console</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction.html"><a href="introduction.html#script"><i class="fa fa-check"></i><b>3.1.2</b> Script</a></li>
<li class="chapter" data-level="3.1.3" data-path="introduction.html"><a href="introduction.html#environment-and-history"><i class="fa fa-check"></i><b>3.1.3</b> Environment and history</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction.html"><a href="introduction.html#importing-data-into-rstudio-cloud"><i class="fa fa-check"></i><b>3.2</b> Importing data into Rstudio cloud</a><ul>
<li class="chapter" data-level="3.2.1" data-path="introduction.html"><a href="introduction.html#upload-the-data-into-rstudio-cloud"><i class="fa fa-check"></i><b>3.2.1</b> Upload the data into Rstudio Cloud</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction.html"><a href="introduction.html#import-data"><i class="fa fa-check"></i><b>3.2.2</b> Import data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>4</b> Packages</a><ul>
<li class="chapter" data-level="4.1" data-path="packages.html"><a href="packages.html#installing-packages"><i class="fa fa-check"></i><b>4.1</b> Installing packages</a><ul>
<li class="chapter" data-level="4.1.1" data-path="packages.html"><a href="packages.html#installing-packages-using-point-and-click-gui"><i class="fa fa-check"></i><b>4.1.1</b> Installing packages using point and click (GUI)</a></li>
<li class="chapter" data-level="4.1.2" data-path="packages.html"><a href="packages.html#installing-packages-using-code"><i class="fa fa-check"></i><b>4.1.2</b> Installing packages using code</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="packages.html"><a href="packages.html#loading-packages"><i class="fa fa-check"></i><b>4.2</b> Loading Packages</a></li>
<li class="chapter" data-level="4.3" data-path="packages.html"><a href="packages.html#misc"><i class="fa fa-check"></i><b>4.3</b> Misc</a><ul>
<li class="chapter" data-level="4.3.1" data-path="packages.html"><a href="packages.html#restarting-r"><i class="fa fa-check"></i><b>4.3.1</b> Restarting R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="picturing-data.html"><a href="picturing-data.html"><i class="fa fa-check"></i><b>5</b> Picturing Data</a><ul>
<li class="chapter" data-level="5.1" data-path="picturing-data.html"><a href="picturing-data.html#histograms"><i class="fa fa-check"></i><b>5.1</b> Histograms</a><ul>
<li class="chapter" data-level="5.1.1" data-path="picturing-data.html"><a href="picturing-data.html#histograms-with-base-r"><i class="fa fa-check"></i><b>5.1.1</b> Histograms with base R</a></li>
<li class="chapter" data-level="5.1.2" data-path="picturing-data.html"><a href="picturing-data.html#histograms-with-tidyverse"><i class="fa fa-check"></i><b>5.1.2</b> Histograms with tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="picturing-data.html"><a href="picturing-data.html#scatterplots"><i class="fa fa-check"></i><b>5.2</b> Scatterplots</a><ul>
<li class="chapter" data-level="5.2.1" data-path="picturing-data.html"><a href="picturing-data.html#two-continuous-variables"><i class="fa fa-check"></i><b>5.2.1</b> Two continuous variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="picturing-data.html"><a href="picturing-data.html#one-continuous-and-one-categorical-variable"><i class="fa fa-check"></i><b>5.2.2</b> One continuous and one categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="picturing-data.html"><a href="picturing-data.html#additional-resources"><i class="fa fa-check"></i><b>5.3</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>6</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-using-tidyverse-and-psych-packages."><i class="fa fa-check"></i><b>6.1</b> Descriptive statistics using Tidyverse and Psych packages.</a></li>
<li class="chapter" data-level="6.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-using-base-r"><i class="fa fa-check"></i><b>6.2</b> Descriptive statistics using base R</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="measurement.html"><a href="measurement.html"><i class="fa fa-check"></i><b>7</b> Measurement</a><ul>
<li class="chapter" data-level="7.1" data-path="measurement.html"><a href="measurement.html#a-brief-introduction-to-spreadsheets-and-some-brief-review-of-previous-material"><i class="fa fa-check"></i><b>7.1</b> A brief introduction to spreadsheets (and some brief review of previous material)</a></li>
<li class="chapter" data-level="7.2" data-path="measurement.html"><a href="measurement.html#reliability"><i class="fa fa-check"></i><b>7.2</b> Reliability</a><ul>
<li class="chapter" data-level="7.2.1" data-path="measurement.html"><a href="measurement.html#internal-reliability"><i class="fa fa-check"></i><b>7.2.1</b> Internal reliability</a></li>
<li class="chapter" data-level="7.2.2" data-path="measurement.html"><a href="measurement.html#test-retest-reliability"><i class="fa fa-check"></i><b>7.2.2</b> Test-retest reliability</a></li>
<li class="chapter" data-level="7.2.3" data-path="measurement.html"><a href="measurement.html#interrater-reliability"><i class="fa fa-check"></i><b>7.2.3</b> Interrater reliability</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="measurement.html"><a href="measurement.html#validity"><i class="fa fa-check"></i><b>7.3</b> Validity</a><ul>
<li class="chapter" data-level="7.3.1" data-path="measurement.html"><a href="measurement.html#criterion-validity"><i class="fa fa-check"></i><b>7.3.1</b> Criterion validity</a></li>
<li class="chapter" data-level="7.3.2" data-path="measurement.html"><a href="measurement.html#convergent-and-discriminant-validity"><i class="fa fa-check"></i><b>7.3.2</b> Convergent and Discriminant Validity</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="measurement.html"><a href="measurement.html#homework"><i class="fa fa-check"></i><b>7.4</b> Homework</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="basic-data-transformations.html"><a href="basic-data-transformations.html"><i class="fa fa-check"></i><b>8</b> Basic Data Transformations</a></li>
<li class="chapter" data-level="9" data-path="bivariate-correlational-research.html"><a href="bivariate-correlational-research.html"><i class="fa fa-check"></i><b>9</b> Bivariate correlational research</a><ul>
<li class="chapter" data-level="9.1" data-path="bivariate-correlational-research.html"><a href="bivariate-correlational-research.html#association-claim-with-two-quantitative-variables"><i class="fa fa-check"></i><b>9.1</b> Association claim with two quantitative variables</a></li>
<li class="chapter" data-level="9.2" data-path="bivariate-correlational-research.html"><a href="bivariate-correlational-research.html#association-claim-with-one-quantitative-variable-and-one-categorical-variable"><i class="fa fa-check"></i><b>9.2</b> Association claim with one quantitative variable and one categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html"><i class="fa fa-check"></i><b>10</b> Multivariate correlational research</a><ul>
<li class="chapter" data-level="10.1" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#get-to-know-data"><i class="fa fa-check"></i><b>10.1</b> Get to know data</a></li>
<li class="chapter" data-level="10.2" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#multiple-regression"><i class="fa fa-check"></i><b>10.2</b> Multiple regression</a><ul>
<li class="chapter" data-level="10.2.1" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#optional-additional-information"><i class="fa fa-check"></i><b>10.2.1</b> Optional additional information</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="multivariate-correlational-research.html"><a href="multivariate-correlational-research.html#mediation-and-moderation"><i class="fa fa-check"></i><b>10.3</b> Mediation and moderation</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="simple-experiment.html"><a href="simple-experiment.html"><i class="fa fa-check"></i><b>11</b> Simple experiment</a><ul>
<li class="chapter" data-level="11.1" data-path="simple-experiment.html"><a href="simple-experiment.html#two-groups---independent-group-design"><i class="fa fa-check"></i><b>11.1</b> Two groups - Independent group design</a><ul>
<li class="chapter" data-level="11.1.1" data-path="simple-experiment.html"><a href="simple-experiment.html#research-question"><i class="fa fa-check"></i><b>11.1.1</b> Research question</a></li>
<li class="chapter" data-level="11.1.2" data-path="simple-experiment.html"><a href="simple-experiment.html#method"><i class="fa fa-check"></i><b>11.1.2</b> Method</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="simple-experiment.html"><a href="simple-experiment.html#two-groups---dependent-group-design"><i class="fa fa-check"></i><b>11.2</b> Two groups - Dependent group design</a><ul>
<li class="chapter" data-level="11.2.1" data-path="simple-experiment.html"><a href="simple-experiment.html#research-question-1"><i class="fa fa-check"></i><b>11.2.1</b> Research question</a></li>
<li class="chapter" data-level="11.2.2" data-path="simple-experiment.html"><a href="simple-experiment.html#method-1"><i class="fa fa-check"></i><b>11.2.2</b> Method</a></li>
<li class="chapter" data-level="11.2.3" data-path="simple-experiment.html"><a href="simple-experiment.html#data-analysis"><i class="fa fa-check"></i><b>11.2.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="simple-experiment.html"><a href="simple-experiment.html#more-than-two-groups---independent-group-design"><i class="fa fa-check"></i><b>11.3</b> More than two groups - Independent group design</a><ul>
<li class="chapter" data-level="11.3.1" data-path="simple-experiment.html"><a href="simple-experiment.html#research-question-2"><i class="fa fa-check"></i><b>11.3.1</b> Research question</a></li>
<li class="chapter" data-level="11.3.2" data-path="simple-experiment.html"><a href="simple-experiment.html#method-2"><i class="fa fa-check"></i><b>11.3.2</b> Method</a></li>
<li class="chapter" data-level="11.3.3" data-path="simple-experiment.html"><a href="simple-experiment.html#data-analysis-1"><i class="fa fa-check"></i><b>11.3.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="simple-experiment.html"><a href="simple-experiment.html#more-than-two-groups---dependent-group-design"><i class="fa fa-check"></i><b>11.4</b> More than two groups - Dependent group design</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html"><i class="fa fa-check"></i><b>12</b> Experiments with more than one IV</a><ul>
<li class="chapter" data-level="12.1" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#independent-group-factorial-design"><i class="fa fa-check"></i><b>12.1</b> Independent-group factorial design</a></li>
<li class="chapter" data-level="12.2" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#within-group-factorial-design"><i class="fa fa-check"></i><b>12.2</b> Within-group factorial design</a></li>
<li class="chapter" data-level="12.3" data-path="experiments-with-more-than-one-iv.html"><a href="experiments-with-more-than-one-iv.html#mixed-factorial-design"><i class="fa fa-check"></i><b>12.3</b> Mixed factorial design</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>13</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tools for Working with Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-experiment" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Simple experiment</h1>
<div id="two-groups---independent-group-design" class="section level2">
<h2><span class="header-section-number">11.1</span> Two groups - Independent group design</h2>
<div id="research-question" class="section level3">
<h3><span class="header-section-number">11.1.1</span> Research question</h3>
<p>How do you get children to help around the house? Theory and past research indicate that using noun words, like helper, sends a signal that the noun is part of a person’s identity. Bryan, Master, and Walton (2014) tested this in young children and found that the kids helped more when an experimenter talked to them about “being a helper” (noun condition) compared to when the experimenter talked to them about “helping” (verb condition).</p>
</div>
<div id="method" class="section level3">
<h3><span class="header-section-number">11.1.2</span> Method</h3>
<p>Imagine you replicated this study. You recruited 80 three-to four-year-olds from local daycare centers. Participants were randomly assigned to be in the helper condition (i.e. the noun condition) or the helping condition (i.e. the verb condition). An experimenter first talked to the children about helping.</p>
<p>The children in the helper condition heard: “Some children choose to be helpers. You could be a helper when someone needs to pick things up, you could be a helper when someone has a job to do, and you could be a helper when someone needs help.”</p>
<p>The children in the helping condition heard: “Some children choose to help. You could help when someone needs to pick things up, you could help when someone has a job to do, and you could help when someone needs help.”</p>
<p>Next all of the children were given toys and told they can play. While they were playing, the experimenter provided 9 helping opportunities - for example, pick up a mess, open a container, put away toys, pick up crayons that had spilled on the floor. The experimenters counted the number of times the children stop playing to help.</p>
<div id="set-up---open-data-and-load-the-neccessary-packages." class="section level4">
<h4><span class="header-section-number">11.1.2.1</span> 1. Set up - open data and load the neccessary packages.</h4>
<p>Open the helpwords.csv data (which can be found on D2L).</p>
<p>After you load it into your RStudio cloud project, open the data with the IMPORT DATASET point and click method, or with this code:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="simple-experiment.html#cb1-1"></a><span class="kw">library</span>(readr)</span>
<span id="cb1-2"><a href="simple-experiment.html#cb1-2"></a>helpex &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;helpex.csv&quot;</span>)</span></code></pre></div>
<p>Note that for the condition variable: 1 = noun - “being a helper” and 2 = verb - “helping”.</p>
<p>Then load the tidyverse and psych packages with this code:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="simple-experiment.html#cb2-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="simple-experiment.html#cb2-2"></a><span class="kw">library</span>(psych)</span></code></pre></div>
</div>
<div id="run-descriptive-statistics" class="section level4">
<h4><span class="header-section-number">11.1.2.2</span> 2. Run descriptive statistics</h4>
<p>Let’s first compute measures of central tendency and variability by condition. To do this we will use the <code>describeBy()</code> function of the psych package, which report basic summary statistics by a grouping variable.</p>
<p>Let’s do this here without the Tidyverse pipe (as we have in the past). Using base R, the <code>describeBy()</code> function takes the form of (DV, IV):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="simple-experiment.html#cb3-1"></a><span class="kw">describeBy</span>(helpex<span class="op">$</span>numhelp, helpex<span class="op">$</span>condition)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: 1
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 40 5.12 1.71      5    5.06 1.48   2   9     7 0.23    -0.67 0.27
## ------------------------------------------------------------ 
## group: 2
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 40 2.58 1.65    2.5    2.56 2.22   0   6     6 0.11    -0.98 0.26</code></pre>
<p>We can see that the children in the helper (noun) condition helped an average of 5.12 times (SD = 1.71, range = 2 - 9), while the children in the helping (verb) condition helped an average of 2.85 (SD = 1.65, range = 0 - 6). The results show that the minimum and maximum values are all within the range of possible values.</p>
</div>
<div id="look-at-data" class="section level4">
<h4><span class="header-section-number">11.1.2.3</span> 3. Look at data</h4>
<p>Next let’s look at the data. Let’s first run histograms (again - by level of the IV).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="simple-experiment.html#cb5-1"></a><span class="kw">ggplot</span> (helpex, <span class="kw">aes</span> (<span class="dt">x=</span>numhelp)) <span class="op">+</span></span>
<span id="cb5-2"><a href="simple-experiment.html#cb5-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb5-3"><a href="simple-experiment.html#cb5-3"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="kw">as.factor</span>(condition))</span></code></pre></div>
<p><img src="Tools-for-Working-with-Data_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The histograms show that the data in each group is roughly mound shaped, so they should meet the assumption of normality (this will be tested next), and that there are no outliers.</p>
</div>
<div id="stats" class="section level4">
<h4><span class="header-section-number">11.1.2.4</span> 4. Stats</h4>
<p>First test normality with a Shapiro-Wilk test:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="simple-experiment.html#cb6-1"></a>helpex <span class="op">%&gt;%</span></span>
<span id="cb6-2"><a href="simple-experiment.html#cb6-2"></a><span class="st">  </span><span class="kw">group_by</span>(condition) <span class="op">%&gt;%</span></span>
<span id="cb6-3"><a href="simple-experiment.html#cb6-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">statistic =</span> <span class="kw">shapiro.test</span>(numhelp)<span class="op">$</span>statistic,</span>
<span id="cb6-4"><a href="simple-experiment.html#cb6-4"></a>            <span class="dt">p.value =</span> <span class="kw">shapiro.test</span>(numhelp)<span class="op">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   condition statistic p.value
##       &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1         1     0.961  0.179 
## 2         2     0.945  0.0510</code></pre>
<p>A significant test of normality (Shapiro-Wilk test) indicates that the data is not normally distributed. With non-normal data, a Wilcoxon-Mann-Whitney U test should be used, which is a nonparametric alternative to the independent-sample t-test.</p>
<p>Then test the equality of the group variances with a Levene’s test. Remember that the levene test uses the car package, so let’s first load that package.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="simple-experiment.html#cb8-1"></a><span class="kw">library</span>(car) </span>
<span id="cb8-2"><a href="simple-experiment.html#cb8-2"></a><span class="kw">leveneTest</span>(numhelp <span class="op">~</span><span class="st"> </span><span class="kw">as.factor</span>(condition), <span class="dt">data =</span> helpex)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.0519 0.8204
##       78</code></pre>
<p>A significant test of equality of variance (Levene’s test) means that group variances are different from each other, and in the next step you should account for the unequal variances by using the Welch t-test option.</p>
<p>Then let’s unload the car package becuase it can interver with the tidyverse and psyc packages.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="simple-experiment.html#cb10-1"></a><span class="kw">detach</span>(<span class="st">&quot;package:car&quot;</span>, unload<span class="op">-</span><span class="ot">TRUE</span>)</span></code></pre></div>
<p>In this example, the test of normality and equality of variance were both nonsignificant. This means that in the next step you should use a Student’s t-test, which assumes that group data are normally distributed and that variances are equal.</p>
<p>Next use the t-test function to find the CI and NHST with this base R code:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="simple-experiment.html#cb11-1"></a><span class="kw">t.test</span>(numhelp <span class="op">~</span><span class="st"> </span>condition, <span class="dt">data =</span> helpex, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  numhelp by condition
## t = 6.788, df = 78, p-value = 1.989e-09
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  1.802115 3.297885
## sample estimates:
## mean in group 1 mean in group 2 
##           5.125           2.575</code></pre>
<p>The results show that the 95% CI is 1.802115 to 3.297885, which means that the true difference in the number of words remembered based on the level of processing is likely to be between about 1.5 and 3 helping behaviors.</p>
<p>The results also report that t = 6.788, df = 78, p-value = 1.989e-09 - so the difference is statistically significant.</p>
<p>Next find the effect size using the effsize package with this code:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="simple-experiment.html#cb13-1"></a><span class="kw">library</span>(effsize) </span>
<span id="cb13-2"><a href="simple-experiment.html#cb13-2"></a></span>
<span id="cb13-3"><a href="simple-experiment.html#cb13-3"></a><span class="kw">cohen.d</span>(numhelp <span class="op">~</span><span class="st"> </span><span class="kw">as.factor</span>(condition), <span class="dt">data =</span> helpex)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 1.517847 (large)
## 95 percent confidence interval:
##    lower    upper 
## 1.012631 2.023064</code></pre>
<p>The cohen’s d is 1.5, which is a large effect. The 95% CI is 1.012631 to 2.023064, which is pretty big - reflecting a degreee of uncertainity about the true effect size.</p>
<p>We could also run a scatterplot to see the mean and degree of overlap of data.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="simple-experiment.html#cb15-1"></a><span class="kw">ggplot</span>(helpex, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">as.factor</span>(condition), <span class="dt">y =</span> numhelp)) <span class="op">+</span></span>
<span id="cb15-2"><a href="simple-experiment.html#cb15-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="op">+</span></span>
<span id="cb15-3"><a href="simple-experiment.html#cb15-3"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_cl_normal)</span></code></pre></div>
<p><img src="Tools-for-Working-with-Data_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="apa-stye-write-up" class="section level4">
<h4><span class="header-section-number">11.1.2.5</span> 5. APA-stye write up</h4>
<p>Children in the helper condition (M = 5.12, SD = 1.71) helped more than those in the helping condition (M = 2.85, SD = 1.65).</p>
<p>Therefore, the average difference in the number of words recalled between the groups was 2.55 helping behaviors. The 95%CI on this difference was 1.80 to 3.30 helping behaviors. This CI means that the true difference in the number of words remembered based on the level of processing is likely to be between about 1.5 and 3 helping behaviors.</p>
<p>The standardized effect size of the difference between deep and shallow processing was d = 1.52 (CI.95: 1.01 to 2.02). This effect would be classified by Cohen’s conventions as large.
These 95%CIs do not contain zero, so we can conclude that the difference between the two conditions is statistically significant (t(78) = 6.79, p &lt; .001).</p>
</div>
</div>
</div>
<div id="two-groups---dependent-group-design" class="section level2">
<h2><span class="header-section-number">11.2</span> Two groups - Dependent group design</h2>
<div id="research-question-1" class="section level3">
<h3><span class="header-section-number">11.2.1</span> Research question</h3>
<p>Do fidget spinners help you concentrate? Soares and Storm (2019) asked college-aged student to watch an educational video with and without a fidget spinners. They found that participants remembered more information about the video they watched without the fidget spinner than the video they watched with it.</p>
</div>
<div id="method-1" class="section level3">
<h3><span class="header-section-number">11.2.2</span> Method</h3>
<p>Imagine you replicate Soares and Storm (2019) with a convenience sample of 20 classmates and friends. Participants watched two educational videos about lesser known historical figures. Each video was about 10 minutes. Participants were run individually.</p>
<p>The order of the conditions was counterbalanced across participants so that half of the participants were given the fidget spinner while watching the first video and not the second video. The other half of the participants watched the first video without the fidget spinner and were given the fidget spinner for the second video.</p>
<p>After each video participants completed an unrelated task for 5 minutes and then were given a 15 item fill in the blank test about the video content.</p>
</div>
<div id="data-analysis" class="section level3">
<h3><span class="header-section-number">11.2.3</span> Data analysis</h3>
<p>You should first open the data in R. Then you should get to know your data by using graphs to look at the data and running descriptive statistics. Next you should calculate the confidence interval, effect size, and null hypothesis significance test (NHST).</p>
<div id="open-data-and-load-the-neccessary-packages." class="section level4">
<h4><span class="header-section-number">11.2.3.1</span> Open data and load the neccessary packages.</h4>
<p>Then open the data, which is in fidget.csv on D2L.</p>
<p>After you load it into your RStudio cloud project, open the data with the IMPORT DATASET point and click method, or with this code:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="simple-experiment.html#cb16-1"></a><span class="kw">library</span>(readr)</span>
<span id="cb16-2"><a href="simple-experiment.html#cb16-2"></a>fidex &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;fidex.csv&quot;</span>)</span></code></pre></div>
<p>Note the layout of the data here. Let’s use the <code>head()</code> function to look at the first 3 rows of the dataset:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="simple-experiment.html#cb17-1"></a><span class="kw">head</span>(fidex, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##      id wofid  wfid
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     6     3
## 2     2    15     4
## 3     3     9     3</code></pre>
<p>Remember that in a spreadsheet, each row typically represents an individual participant in the study. So, with a within subject design, the IV data will be split into to columns. In this example the wfid is the test scores for the video watched with the fidget spinner and the wofid is the test scores for the video watched without the fidget spinner.</p>
<p>A column with the difference between the two levels of the IV is needed for within subject data analysis. So, let’s create it now using the <code>mutate()</code> function (which is part of the tidyverse package)</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="simple-experiment.html#cb19-1"></a>fidex &lt;-<span class="st"> </span>fidex <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb19-2"><a href="simple-experiment.html#cb19-2"></a><span class="st">            </span><span class="kw">mutate</span>(<span class="dt">diff =</span> wofid <span class="op">-</span><span class="st"> </span>wfid)</span>
<span id="cb19-3"><a href="simple-experiment.html#cb19-3"></a></span>
<span id="cb19-4"><a href="simple-experiment.html#cb19-4"></a><span class="kw">head</span>(fidex, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##      id wofid  wfid  diff
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     6     3     3
## 2     2    15     4    11
## 3     3     9     3     6</code></pre>
<p>The first participant scored a 6 on the test about the video he/she watched without the fidget spinner and a 3 on the test of the video watched with the fidget spinner. The difference between the scores is 3 points.</p>
</div>
<div id="descriptive-statistics-and-assumptions" class="section level4">
<h4><span class="header-section-number">11.2.3.2</span> Descriptive statistics and assumptions</h4>
<p>Let’s first compute measures of central tendency and variability.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="simple-experiment.html#cb21-1"></a>fidex <span class="op">%&gt;%</span></span>
<span id="cb21-2"><a href="simple-experiment.html#cb21-2"></a><span class="st">  </span><span class="kw">select</span> (wofid, wfid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb21-3"><a href="simple-experiment.html#cb21-3"></a><span class="st">  </span><span class="kw">describe</span>()</span></code></pre></div>
<pre><code>##       vars  n  mean   sd median trimmed  mad min max range  skew kurtosis   se
## wofid    1 20 10.55 3.25   10.5   10.62 3.71   5  15    10 -0.17    -1.39 0.73
## wfid     2 20  5.60 3.36    6.5    5.69 4.45   0  10    10 -0.22    -1.49 0.75</code></pre>
<p>We can see that the children in the helper (noun) condition helped an average of 5.12 times (SD = 1.71, range = 2 - 9), while the children in the helping (verb) condition helped an average of 2.85 (SD = 1.65, range = 0 - 6). The results show that the minimum and maximum values are all within the range of possible values.</p>
<p>First test normality of the difference scores with a Shapiro-Wilk test:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="simple-experiment.html#cb23-1"></a><span class="kw">shapiro.test</span>(fidex<span class="op">$</span>diff)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fidex$diff
## W = 0.97287, p-value = 0.8139</code></pre>
<p>A significant test of normality (Shapiro-Wilk test) indicates that the data is not normally distributed. With non-normal data, a Paired Samples Wilcoxon test should be used, which is a nonparametric alternative to the related-sample t-test.</p>
<p>In this example, the test of equality of variance is nonsignificant. This means that in the next step you should use a Student’s t-test, which assumes that group data are normally distributed.</p>
</div>
<div id="stats-1" class="section level4">
<h4><span class="header-section-number">11.2.3.3</span> Stats</h4>
<p>Use the t-test function to find the CI and NHST with this base R code:</p>
<p><code>t.test(fidex$wofid, fidex$wfid, paired = TRUE)</code>
- The within-subjects t-test uses the same <code>t.test()</code> function as you did with independent samples. However, this time you have to use the form of: level1, level2<br />
- I also think you have to direct R to the variable with the $ method (I could not get this to run with the data = )<br />
- The <code>paired=TRUE</code> tells r that it is a within subjects design</p>
<p>The results show that the 95% CI is 2.910114 to 6.989886, which means that the true difference in the number of correct test questions remembered based on fidget spinner use is likely to be between about 3 and 7 correct questions.</p>
<p>The results also report that t = 5.0789, df = 19, p-value = 6.667e-05 - so the difference is statistically significant.</p>
<p>Next find the effect size using the effsize package. Here is the code:</p>
<p><code>library(effsize)</code><br />
<code>cohen.d(fidex$wofid, fidex$wfid, paired=TRUE)</code></p>
<ul>
<li>Again, with within-subjects the cohens.d function takes the form of: level1, level2<br />
</li>
<li>The <code>paired=TRUE</code> tells r that it is a within subjects design</li>
</ul>
<p>The effect size is 1.496451, which is large. The 95% CI is 0.6280516 to 2.3648508, suggesting there is a high level of uncertainity in the size of the effect here.</p>
</div>
<div id="apa-style-write-up" class="section level4">
<h4><span class="header-section-number">11.2.3.4</span> 5. APA-style write up</h4>
<p>Participants remembered more information about the video they watched without the fidget spinner (M = 10.50, SD = 3.25) compared to the video that they watch with the fidget spinner (M = 5.60, SD = 3.36).</p>
<p>Therefore, the average difference in the number of correct test questions between the groups was 4.9 questions. The 95%CI on this difference was 2.91 to 6.99 correct questions. This CI means that the true difference in the number of correct test questions remembered based fidget spinner use is likely to be between about 3 and 7 correct questions.</p>
<p>The standardized effect size of the difference between test score without and with fidget spinners was d = 1.50 (CI.95: 0.63 to 2.36). This effect would be classified by Cohen’s conventions as large.</p>
<p>These 95%CIs do not contain zero, so we can conclude that the difference between the two conditions is statistically significant (t(19) = 5.08, p &lt; .001).</p>
<p>ADD BONUS MATERIAL?</p>
</div>
</div>
</div>
<div id="more-than-two-groups---independent-group-design" class="section level2">
<h2><span class="header-section-number">11.3</span> More than two groups - Independent group design</h2>
<div id="research-question-2" class="section level3">
<h3><span class="header-section-number">11.3.1</span> Research question</h3>
<p>Does the method of note-taking influence test performance? <a href="https://cpb-us-w2.wpmucdn.com/sites.udel.edu/dist/6/132/files/2010/11/Psychological-Science-2014-Mueller-0956797614524581-1u0h0yu.pdf0">Mueller and Oppenheimer (2014)</a> report that</p>
<p>Morehead, Dunlosky, and Rawson (2019) conducted a replication plus extension of Mueller and Oppenhiemer’s (2014) study.</p>
<p>They posted their data (<a href="https://osf.io/dyga5/?view_only=843c2187b4894aefbfc6218b2d6eaed4" class="uri">https://osf.io/dyga5/?view_only=843c2187b4894aefbfc6218b2d6eaed4</a>)</p>
</div>
<div id="method-2" class="section level3">
<h3><span class="header-section-number">11.3.2</span> Method</h3>
<p>They recruited 193 undergraduate students to participate in their study for course credit. Following the procedure of Mueller and Oppenhiemer (2014) participants watched TED talks on uncommon topics.</p>
</div>
<div id="data-analysis-1" class="section level3">
<h3><span class="header-section-number">11.3.3</span> Data analysis</h3>
<div id="open-data-and-load-the-neccessary-packages.-1" class="section level4">
<h4><span class="header-section-number">11.3.3.1</span> Open data and load the neccessary packages.</h4>
<p>Then open the data, which is in Jamesetal.csv on D2L. OR LINK?</p>
<p>After you load it into your RStudio cloud project, open the data with the IMPORT DATASET point and click method, or with this code:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="simple-experiment.html#cb25-1"></a><span class="kw">library</span>(readr)</span>
<span id="cb25-2"><a href="simple-experiment.html#cb25-2"></a>notetaking &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;Data_Experiment1.csv&quot;</span>)</span></code></pre></div>
<p>Here is the codebook LINK.</p>
</div>
<div id="test-the-assumptions" class="section level4">
<h4><span class="header-section-number">11.3.3.2</span> Test the assumptions</h4>
<p>Then load the tidyverse and psych packages with this code:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="simple-experiment.html#cb26-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb26-2"><a href="simple-experiment.html#cb26-2"></a><span class="kw">library</span>(psych)</span></code></pre></div>
</div>
<div id="descriptive-and-test-assumptions" class="section level4">
<h4><span class="header-section-number">11.3.3.3</span> Descriptive and test assumptions</h4>
<p>Let’s first compute measures of central tendency and variability by condition. To do this we will use the <code>describeBy()</code> function of the psych package, which report basic summary statistics by a grouping variable.</p>
<p>Let’s do this here without the Tidyverse pipe (as we have in the past). Using base R, the <code>describeBy()</code> function - which takes the form of (DV, IV):</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="simple-experiment.html#cb27-1"></a><span class="kw">describeBy</span>(notetaking<span class="op">$</span>Test1Tot, notetaking<span class="op">$</span>method)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: 1
##    vars  n mean   sd median trimmed  mad min  max range skew kurtosis   se
## X1    1 32  0.3 0.18    0.3     0.3 0.15   0 0.75  0.75 0.33    -0.22 0.03
## ------------------------------------------------------------ 
## group: 2
##    vars  n mean   sd median trimmed  mad min  max range skew kurtosis   se
## X1    1 31 0.25 0.14   0.25    0.24 0.15   0 0.55  0.55 0.32    -0.69 0.03
## ------------------------------------------------------------ 
## group: 3
##    vars  n mean   sd median trimmed  mad min  max range skew kurtosis   se
## X1    1 31 0.26 0.16   0.25    0.26 0.15   0 0.55  0.55 0.28     -1.1 0.03</code></pre>
<p>Create histograms</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="simple-experiment.html#cb29-1"></a><span class="kw">ggplot</span> (notetaking, <span class="kw">aes</span> (<span class="dt">x=</span>Test1Tot)) <span class="op">+</span></span>
<span id="cb29-2"><a href="simple-experiment.html#cb29-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">.1</span>) <span class="op">+</span></span>
<span id="cb29-3"><a href="simple-experiment.html#cb29-3"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="kw">as.factor</span>(method))</span></code></pre></div>
<pre><code>## Warning: Removed 94 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="Tools-for-Working-with-Data_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>The histograms show that the data in each group is roughly mound shaped, so they should meet the assumption of normality (this will be tested next), and that there are no outliers.</p>
</div>
<div id="stats-2" class="section level4">
<h4><span class="header-section-number">11.3.3.4</span> Stats</h4>
<p>We will use a one way ANOVA to test for difference test performance based on the way in which participants took notes.<br />
In R we can do this with the <code>aov()</code> function, which is part of base R. Similar to the multiple regression, we have to save the ANOVA as an object. Then we will use the <code>summary.aov()</code> to see the results of the ANOVA.</p>
<p>DO I NEED MORE DETIAL HERE?</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="simple-experiment.html#cb31-1"></a>test1tcaov &lt;-<span class="st"> </span><span class="kw">aov</span>(Test1Tot <span class="op">~</span><span class="st"> </span>method, <span class="dt">data =</span> notetaking)</span>
<span id="cb31-2"><a href="simple-experiment.html#cb31-2"></a></span>
<span id="cb31-3"><a href="simple-experiment.html#cb31-3"></a><span class="kw">summary</span>(test1tcaov)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## method       1  0.024 0.02397   0.933  0.337
## Residuals   92  2.364 0.02569               
## 94 observations deleted due to missingness</code></pre>
<p>The results show that the p-value associated with the F-value is greater than .05 - failing to reject the null (the null here is that all of the group means are the same). This means that there is no difference in test performance.</p>
</div>
</div>
</div>
<div id="more-than-two-groups---dependent-group-design" class="section level2">
<h2><span class="header-section-number">11.4</span> More than two groups - Dependent group design</h2>
<p>could add another condition to the last example…. replication plus extension</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multivariate-correlational-research.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="experiments-with-more-than-one-iv.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/nsorha/potential-barnacle/edit/master/simexper.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Tools for Working with Data.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
